// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xdgcupnmpowyibywyjid.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhkZ2N1cG5tcG93eWlieXd5amlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE4OTQ0MzQsImV4cCI6MjA4NzQ3MDQzNH0.Kq_5f4mCbZOlSi33N4RwQYxZNuUeUNoC1hLnIYNeHrU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});